version: '3.8'

services:

  pg-container:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=softpethouse
    volumes:
      - /db_data:/var/lib/postgresql/data
    networks:
      - pg-network
    
  pgadmin-container:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - pg-network

  usuario-api:
    image: softpethouse/usuario-api
    ports:
      - "8081:8081"
    networks:
      - pg-network

  pet-api:
    image: softpethouse/pet-api
    ports:
      - "8082:8082"
    networks:
      - pg-network

  historicopet-api:
    image: softpethouse/historicopet-api
    ports:
      - "8083:8083"
    networks:
      - pg-network

networks: 
  pg-network:
    driver: bridge